version: '2'
services:
  mqclient:
    image: ${REPO}mqclient:${MQ_VERSION}
    build: ./mqclient-${MQ_VERSION}
  iib:
    image: ${REPO}iib-runtime:${IIB_VERSION}
    build: ./iib-${IIB_VERSION}/
  iib-mqclient:
    image: ${REPO}iib-runtime:${IIB_VERSION}-mqclient
    build: ./iib-${IIB_VERSION}-mqclient/
    environment:
      - IIB_LICENSE=accept
      - IIB_ADMINPW=password
      - IIB_OBSERVERPW=password
      - IIB_TRACEMODE=off
